## Broadcasting بين (10,) و (10,1)

In [ ]:
import numpy as np
np.random.seed(42)

a = np.arange(10)          # shape (10,)
b = np.arange(10).reshape(10, 1)   # shape (10,1)

c = a + b                  # broadcasting -> (10,10)

print("a.shape =", a.shape)
print("b.shape =", b.shape)
print("c.shape =", c.shape)
print(c)


a.shape = (10,)
b.shape = (10, 1)
c.shape = (10, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


## np.where

In [117]:
np.random.seed(42)  # حتى تطلع نفس النتائج كل مرة (اختياري)

grades = np.random.randint(0, 101, size=30)  # 30 طالب
status = np.where(grades >= 50, "Pass", "Fail")

print("Grades:", grades)
print("Status:", status)

Grades: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
Status: ['Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass'
 'Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Fail'
 'Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail']


## clip

In [118]:
bad_grades = np.array([20, 55, -10, 130, 99, 101, 0])
fixed_grades = np.clip(bad_grades, 0, 100)

print("Bad:", bad_grades)
print("Fixed:", fixed_grades)

Bad: [ 20  55 -10 130  99 101   0]
Fixed: [ 20  55   0 100  99 100   0]


## Loop vs Vectorization

In [119]:
import time

N = 1_000_000
x = np.random.randint(0, 101, size=N)

# 1) Loop
t0 = time.time()
loop_out = np.empty_like(x)
for i, v in enumerate(x):
    loop_out[i] = 1 if v >= 50 else 0
t1 = time.time()

# 2) Vectorization
t2 = time.time()
vec_out = (x >= 50).astype(int)
t3 = time.time()

print("Loop time:", round(t1 - t0, 4), "sec")
print("Vector time:", round(t3 - t2, 4), "sec")
print("Same result?", np.array_equal(loop_out, vec_out))


Loop time: 0.14 sec
Vector time: 0.002 sec
Same result? True


## Pass/Fail

In [120]:
grades = np.random.randint(0,101,size=30)
status = np.where(grades >= 50, "pass" , "fail")

passed = np.sum(grades >= 50)
failed = np.sum(grades < 50)
total = grades.size

pass_rate = (passed / total) * 100
fail_rate = (failed / total) * 100

print("=== Small Report ===")
print("Total students:", total)
print("Passed:", passed)
print("Failed:", failed)
print("Pass rate:", round(pass_rate, 2), "%")
print("Fail rate:", round(fail_rate, 2), "%")

=== Small Report ===
Total students: 30
Passed: 18
Failed: 12
Pass rate: 60.0 %
Fail rate: 40.0 %


## Final Summary

In [127]:
import pandas as pd

df = pd.DataFrame({
    "Grade": grades,
    "Status": status
})

passed = (df["Status"] == "pass").sum()
failed = (df["Status"] == "fail").sum()
total = len(df)

pass_pct = (passed / total) * 100
fail_pct = (failed / total) * 100

print("=== Final Report ===")
print("Total students:", total)
print("Passed:", passed)
print("Failed:", failed)
print("Pass %:", round(pass_pct, 2))
print("Fail %:", round(fail_pct, 2))


=== Final Report ===
Total students: 30
Passed: 18
Failed: 12
Pass %: 60.0
Fail %: 40.0
